### ISSUE TITLE
Error: Uncaught Error: Class "Google\Protobuf\Internal\Message" not found

### ISSUE THREAD

**Issue by san-kumar** [upstox/upstox-php#13]
Hi,

When I run the websocket_client.php I get this error:

```
Connection successful!
PHP Fatal error:  Uncaught Error: Class "Google\Protobuf\Internal\Message" not found in /home/work/tmp/upstox-php-master/examples/websocket/market_data/protobuf/Com/Upstox/Marketdatafeeder/Rpc/Proto/FeedResponse.php:14
Stack trace:
#0 /home/work/tmp/upstox-php-master/examples/websocket/market_data/vendor/composer/ClassLoader.php(576): include()
#1 /home/work/tmp/upstox-php-master/examples/websocket/market_data/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 /home/work/tmp/upstox-php-master/examples/websocket/market_data/websocket_client.php(19): Composer\Autoload\ClassLoader->loadClass()
#3 /home/work/tmp/upstox-php-master/examples/websocket/market_data/websocket_client.php(94): decodeProtobuf()
#4 /home/work/tmp/upstox-php-master/examples/websocket/market_data/websocket_client.php(102): fetchMarketUpdates()
#5 {main}
  thrown in /home/work/tmp/upstox-php-master/examples/websocket/market_data/protobuf/Com/Upstox/Marketdatafeeder/Rpc/Proto/FeedResponse.php on line 14
```

I did run `composer install` and it was successful. But looks like some issue with the library.

Any ideas?

**Comment by san-kumar** [comment]
Ok, I figured it out. `composer.json` inside `market_data` directory needs to be updated with following in the require section:

```
        "google/protobuf": "^3.25"
```

Let me know if you guys accept pull requests.

**Comment by KetanGupta12** [comment]
@san-kumar 

Are you still experiencing this issue?

If yes, please raise a query on the [Upstox community](https://community.upstox.com/c/developer-api). This is where both our team and the active developer community are diligently checking and responding.

Thanks!
